#
# Message of the plugin

jobs:

  # Help format.
  help:
    format:
      - "&a[Server] &8| &fList of player arguments."
      - ""
      - "&8- &f/jobs join &a[job] [job]..."
      - "&8- &f/jobs leave &a[job] [job]..."
      - "&8- &f/jobs leave-all"
      - "&8- &f/jobs stats"
      - "&8- &f/jobs browse"
      - "&8- &f/jobs info &a[job]"
      - ""
    admin:
      - ""
      - "&c[Admin] &fList of admin arguments"
      - ""
      - "&8- &f/jobs reload"
      - "&8- &f/jobs add-level &c[player] [job] [level]"
      - "&8- &f/jobs set-level &c[player] [job] [level]"
      - "&8- &f/jobs remove-level &c[player] [job] [level]"
      - "&8- &f/jobs set-multiplier &c[number]"
      - "&8- &f/jobs block &a[job/-all]"
      - "&8- &f/jobs unblock &a[job/-all]"

  # Reload message.
  reload: "&a[Server] &8| &fPlugin reloaded."

  join:

    # Message when you join to a job.
    message: "&a[Server] &8| &fYou joined the job. &a%job%"

  leave:

    # Message when you leave a job.
    message: "&a[Server] &8| &fYou left the job. &a%job%"

  leave-all:

    # Message when you leave a job.
    message: "&a[Server] &8| &fYou left all jobs."


  add-level:

    # Message when you add a level in job to a player.
    message: "&a[Server] &8| &fYou add &a%level% &fin &a%job% &fto &a%player%&f."

  remove-level:

    # Message when you remove a level in job to a player.
    message: "&a[Server] &8| &fYou remove &a%level% &fin &a%job% &fto &a%player%&f."

  set-level:

    # Message when you set a level in job to a player.
    message: "&a[Server] &8| &fYou set &a%level% &fin &a%job% &fto &a%player%&f."

  browse:

    # Message when you browse the jobs.
    list:
      - "&a[Server] &8| &fList of jobs:"
      - "&fMiner &8: &fTo break blocks."
      - "&fWoodcutter &8: &fTo break wood blocks."
      - "&fBuilder &8: &fTo build blocks."
      - "&fHunter &8: &fTo kill mobs or player."

  stats:

    # Message when you see your stats.
    message:
      - "&a[Server] &8| &fYour action stats:"
      - "%action_stats% &8- &f%action_name% &8: &f%action_value%"
      - ""
      - "&a[Server] &8| &fYour job stats:"
      - "%job_format% &8- &f%job_name% &8- &fNivel %level% &8: &f%xp%&8/&f%max_xp% "

    stats:

      global:

        miner: "Blocks broken"
        woodcutter: "Blocks broken"
        builder: "Blocks placed"
        hunter: "Items killed"

      item:

        miner: "%data% broken"
        woodcutter: "%data% broken"
        builder: "%data% placed"
        hunter: "%data% killed"

  info:

    # Message when you see the info.
    message:

      # Message when you see the info of your job.
      - "&a[Server] &8|  &fInfo of %job_name%:"
      - "%job_format% &8- &a%item_name% &8- &e%gain_money%$ &8- &f%gain_xp%XP "

  gain:

    # Message when you increment level.
    level: "&a[Server] &8| &fYou incremented of level. &a%new_level%&f."

  multipler:

    # Message when you set a multiplier.
    set: "&a[Server] &8| &FYou set the multiplier &a%multiplier%."

  block:

    all: "&a[Server] &8| &fYou blocked all jobs."
    job: "&a[Server] &8| &fYou blocked the job &a%job%&f."

  unblock:

    all: "&a[Server] &8| &fYou unblocked all jobs."
    block: "&a[Server] &8| &fYou unblock the job &a%job%&f."

error:

  # When the player is using the console.
  console: "Error - No puedes hacer esto en la consola."

  # When the player is using a unknown argument.
  unknown-argument: "&a[Server] &8| &fArgumento desconocido. Usa &a/jobs help &fpara ver los argumentos disponibles."

  # When the player is not putting a necessary argument.
  no-argument: "&a[Server] &8| &fYou doesn't put any argument. Use: &a%usage%&f."

  # When the player doesn't have permission to use the command.
  no-permission: "&a[Server] &8| &fYou don't have permission to use the command."

  # When the player isn't online.
  no-online: "&a[Server] &8| &fThe player isn't online."

  # When you don't write a number.
  unknown-number: "&a[Server] &8| &fUnknown number, put a number."

  # When you put a negative number.
  negative-number: "&a[Server] &8| &fYou put a negative number, put a number mayor to 0."

  # Job error messages:
  #

  # When the player blocked a job.
  blocked-job: "&a[Server] &8| &fThe job is blocked at this moment: &a%job%&f."

  # When the player is not putting a job.
  unknown-job: "&a[Server] &8| &fUnknown job: &a%job%&f."

  # When the player already have a job.
  already-have-job: "&a[Server] &8| &fYou have already joined this job: &a%job%&f."

  # When the player already don't have a job.
  already-leave-job: "&a[Server] &8| &fYou already left or did not join this job: &a%job%."

  # When the player doesn't join a job.
  dont-join-job: "&a[Server] &8| &fYou did not join this job, but we will show you the information from level 1."

  # When the player doesn't join any jobs.
  dont-join-any-jobs: "&a[Server] &8| &fYou did not join any job."

  # When you joined too much jobs.
  limited-jobs: "&a[Server] &8| &fYou joined too much jobs."

  # You reached the max level.
  max-level: "&a[Server] &8| &fYou reached the max level: &a%level%"

  # When you put a level that minor results to 0.
  minor-0: "&a[Server] &8| &fThe level result is minor to 0."
